name: shayefmate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.9.8+1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_object_detection: ^0.15.0
  image_picker: ^1.0.7
  flutter_tts: ^4.2.2
  permission_handler: ^12.0.0+1
  flutter_native_splash: ^2.4.5
  flutter_sound: ^9.2.13
  speech_to_text: ^6.4.0
  audioplayers: ^5.2.1
  image: ^4.0.15
  tflite: ^1.1.2
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/detect.tflite
    - assets/labelmap.txt

dependency_overrides:
  image: ^3.0.2
